image: node

pipelines:
  branches:
    master:
      - step:
          name: Build app
          script:
            - yarn install && yarn build
          artifacts:
            - build/**
            
      - step:
          name: Build function
          script:
            - yarn install && yarn build
          artifacts:
            - functions/lib/**

      - step:
          name: Deploy to Firebase
          deployment: production
          script:
            - pipe: atlassian/firebase-deploy:0.2.1
              variables:
                FIREBASE_TOKEN: $FIREBASE_TOKEN
                PROJECT_ID: $FIREBASE_PROJECT

